spring.application.name=SBProject-Web-app-1

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp


spring.datasource.url=jdbc:mysql://localhost:3306/sb_webapp1_db
spring.datasource.username=root
spring.datasource.password=Me@sqll123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true