spring.application.name=SBProject-Register-Login-Page


spring.datasource.url=jdbc:mysql://localhost:3306/reg_login_thymeleaf_sb
spring.datasource.username=root
spring.datasource.password=Me@sqll123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true