spring.application.name=SBProject-6-Data-JPA

spring.datasource.url=jdbc:mysql://localhost:3306/spring_datajpa_crud_db
spring.datasource.username=root
spring.datasource.password=Me@sqll123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true