spring.application.name=SBProject-RESTful-Web-Services


spring.datasource.url=jdbc:mysql://localhost:3306/restful_api_sb_db
spring.datasource.username=root
spring.datasource.password=Me@sqll123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true