spring.application.name=SBProject-5-JDBC-CRUD

spring.DataSource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.DataSource.url=jdbc:mysql://localhost:3306/springboot_jdbc_db
spring.DataSource.username=root
spring.DataSource.password=Me@sqll123
